### ISSUE TITLE
[Feature Request] Dataview Integration

### ISSUE THREAD

**Issue by eb2ai** [DeabLabs/cannoli#1]
First Issue / Request. This is fun!

It would be awesome if this could use a dataview for information. My preliminary tests all come back that it doesn't recognize that data.

**Comment by blindmansion** [comment]
Thanks for trying out Cannoli!

Yes this is something I'd really like to add. It's near the top of the priority list, and as far as I know it should be feasible. Coming soon!

**Comment by eb2ai** [comment]
Awesome!

**Comment by arminta7** [comment]
Any update on this? It would open up so many possibilities!

**Comment by blindmansion** [comment]
Finally started working on cannoli again, I'm gonna take another look at this. Last time I tried this it started to look much more difficult than I expected, but this indeed would be very cool.

**Comment by blindmansion** [comment]
@eb2ai , @arminta7 Thanks for your patience! This is now implemented as of 1.7
