### ISSUE TITLE
[FR] - GPT 4 Turbo

### ISSUE THREAD

**Issue by arminta7** [DeabLabs/cannoli#13]
Hello! Would love support for GPT4 Turbo.

**Comment by blindmansion** [comment]
Hello! I'll confirm this when I get a chance, but I believe this should already be supported. Cannoli just passes the model string you provide in the settings pane or the config arrow into openai.

Check out the cannoli college canvas about config arrow, and the  list of model strings on the openai docs: https://platform.openai.com/docs/api-reference/chat/streaming

Let me know if the new models cause issues.

**Comment by arminta7** [comment]
I will try again. I had tried simply entering the new model in the settings but received an error. Something about "name" I think? Maybe I did something wrong.

**Comment by blindmansion** [comment]
Looks like the name to reference gpt4 turbo is:
gpt-4-1106-preview

Let me know if that works!

**Comment by blindmansion** [comment]
Thinking about this more and it's possible I have some particular models hard-coded in that are throwing errors.

I'll take a look soon.

**Comment by arminta7** [comment]
Here is the error I get. 

<img width="514" alt="Screenshot 2023-11-07 at 10 24 41" src="https://github.com/DeabLabs/cannoli/assets/7927356/897d984c-73aa-454b-a5a5-e3723f12ad68">

**Comment by blindmansion** [comment]
Oh yea this is an issue on my end. I'll take a look and put together a fix.

**Comment by wwboynton** [comment]
Hi @blindmansion, any update on this? Thanks for creating such a stellar extension. I don't think I'll have time in the next few weeks, but if you're totally swamped, I may eventually be able to look at this and PR it.

**Comment by wwboynton** [comment]
Actually, it was easy to patch. Turns out the models are hardcoded with pricing info. I just slapped another object into the map:
```javascript
    this.modelInfo = {
      "gpt-4": {
        name: "gpt-4",
        promptTokenPrice: 0.03 / 1e3,
        // $0.03 per 1K tokens
        completionTokenPrice: 0.06 / 1e3
        // $0.06 per 1K tokens
      },
      "gpt-3.5-turbo": {
        name: "gpt-3.5-turbo",
        promptTokenPrice: 15e-4 / 1e3,
        // $0.0015 per 1K tokens
        completionTokenPrice: 2e-3 / 1e3
        // $0.002 per 1K tokens
      },
      "gpt-4-1106-preview": {
        name: "gpt-4-1106-preview",
        promptTokenPrice: 0.01 / 1e3,
        completionTokenPrice: 0.06 / 1e3
      }
    };
```

However, I imagine you'd probably want to implement some logic that says "if it's not in modelinfo, run it anyway and don't do any price calculations" or something more elegant so that you're not tied to updating every time the models change. But I hope my comment is useful for anyone who just wants to get it working right now.

**Comment by blindmansion** [comment]
Awesome thanks for finding the fix! And yes, that's exactly the kind behavior i'd like for the model strings. Yea I've been struggling to find time for cannoli the last few weeks, but I should be able to implement this soon.

**Comment by alexzadeh** [comment]
Hi @wwboynton, thanks for sharing the fix. Where do I make the changes? Keen to use Turbo!

Thanks

**Comment by blindmansion** [comment]
Sorry for the delay on this, I'll fix this and release it early next week.

**Comment by blindmansion** [comment]
Oh and if you search up a portion of the code posted above you'll be able to find it if you want to fix it in the meantime. I believe it's on the file run.ts.

**Comment by alexzadeh** [comment]
Hey, thanks, I meant to the Obsidian plugin itself, but it's all good - ChatGPT told me to where to find the main.js file 😊

**Comment by blindmansion** [comment]
This is fixed in the newest release! Sorry for the wait.

**Comment by alexzadeh** [comment]
Thanks!
