### ISSUE TITLE
[Feature Request] documentation on Action Nodes formatting

### ISSUE THREAD

**Issue by solarbotanist** [DeabLabs/cannoli#14]
Amazing work. So much fun! 

I want to make an API call to the new openAI TTS endpoint using an Action node. I can't seem to get the JSON formatted correctly:

```json
{
  "method": "POST",
  "url": "https://api.openai.com/v1/audio/speech",
  "headers": {
    "content-type": "application/json",
    "Authorization": "Bearer myKey"
  },
  "body": {
    "model": "tts-1",
    "input": "{{input}}",
    "voice": "nova"
  }
}
```

I have tried various other options in the place of "body" - all result in a 400 error. 

In Postman I get a successful response in the following configuration:

```HTTP

POST /v1/audio/speech HTTP/1.1
Host: api.openai.com
content-type: application/json
Authorization: Bearer myKey
Content-Length: n

{

    "model": "tts-1",

    "input": "{{input}}",

    "voice": "nova"

}
```

I tried to see how the JSON object is used in the JS to make an API call but I'm a little stuck. 

Would it be possible to provide some documentation on how the Action nodes make the API call based on the JSON object? Would it also be possible to make a call with the content type of x-www-form-urlencoded?

**Comment by solarbotanist** [comment]
My apologies. I realized my mistake. 

```json
  "bodyTemplate": {
    "model": "tts-1",
    "input": "{{input}}",
    "voice": "nova"
  }
```

Formatted like this, I get the error I expected (Unexpected token). Now I just need to find a way to write the response to a file.

**Comment by blindmansion** [comment]
Ok glad you got it resolved! Let me know if you have more questions or bugs with action nodes.

As for writing the response to a file, you should be able to write the response to a note using a reference node, which is just a content node that only contains "{{[[Note name]]}}". Is this what you're talking about?

**Comment by solarbotanist** [comment]
The problem is that with the TTS model the response is an mp3 file not json, so I keep getting errors. But that's not the code's fault of course I'm just trying to do something it's not meant to do.
