### ISSUE TITLE
Image / vision API support

### ISSUE THREAD

**Issue by dev-msp** [DeabLabs/cannoli#16]
Just discovered this, and I both detest and greatly respect that you actually built (and surpassed) something I merely daydreamed about idly one day. Congrats! :D

As of recently, images serve as both LLM input (Vision API beta) and output (DALL-E). Now I can't help but wonder about the potential for image nodes in Cannoli! 

I haven't familiarized myself with the code yet, but in theory I'm very much down to contribute as well.

**Comment by solarbotanist** [comment]
I've been testing vision with the action nodes. got it working like this: 

![TEST vision cno](https://github.com/DeabLabs/cannoli/assets/125293710/411054b8-4cc6-4312-a829-c5517c31ea14)

**Comment by blindmansion** [comment]
Thanks so much for trying cannoli!

Yes this would be awesome, and with all the new API features out it's high on my list.

Also, awesome work solarbotanist, are you saying that this is working as intended, and the images are being sent and received correctly? That's amazing! I always wanted to write an openai action node for the meme, but hadn't yet.

**Comment by solarbotanist** [comment]
Yes everything is working as intended! The action node as described can proces both online image URI's as well as base64 encoded images. 

A base64 encoding function could be implemented in the TS so that images in the vault could be used directly.

**Comment by lightningRalf** [comment]
any updates on this?

**Comment by blindmansion** [comment]
Not yet, but I just looked at the vision docs for OpenAI at least, and it's not as bad as I thought it would be. So maybe not that far off after all.

**Comment by blindmansion** [comment]
Vision is now implemented! All you have to do is embed an image from a url or your vault using markdown syntax: `![[your_image.jpg]]` or `![description](imageurl.com)`

We've also added a built-in dalle action.
