### ISSUE TITLE
after update to 1.5.9 cannolis no longer work

### ISSUE THREAD

**Issue by winne617** [DeabLabs/cannoli#18]
hey, after the update to 1.5.9 cannolis no longer work (at least in my case). nothing happens when i hit "run", regardless of the model. better said, almost nothing happens: the colors of an already run cannoli get reset when you start it. thats it.

**Comment by blindmansion** [comment]
Just released the fix for this, I had forgotten the original gpt-3.5-turbo in the models list.

Thanks for the callout!
