### ISSUE TITLE
[Feature request] Support the operation and debugging of a single module group

### ISSUE THREAD

**Issue by linxizhiri** [DeabLabs/cannoli#21]
Thank the author for developing such an excellent plugin and providing a structured design to implement functions similar to "GPTs".In the actual use process, there is a detail that needs to be improved to enhance the user experience.
Scenario 1: In a complex process, there are usually multiple module function groups.When a user debugs a module group, they can simply execute the module function group currently selected by the mouse using a shortcut key, rather than running the entire process.
Scenario 2: For a complex process, manual intervention is required for the execution results of each stage during the execution process.Otherwise, the final execution results will deviate from the expected user effects.The waste of ineffective computing resources leads to low efficiency.
Based on the above scenario, I hope the author can improve the user experience.Thank you again for providing such plug-in features.I give you a thumbs up!
Similar functionality has been implemented in the plugin "chat stream".You can check the plugin link at  https://github.com/rpggio/obsidian-chat-stream

**Comment by blindmansion** [comment]
@linxizhiri Sorry for the delay on answering this! You can sort of accomplish this by creating a group labeled "cannoli". When you run that canvas, only the nodes inside of the "cannoli" group will be run.
