### ISSUE TITLE
[FR] Set up custom service providers

### ISSUE THREAD

**Issue by wwjCMP** [DeabLabs/cannoli#29]
Reference can be made to the approach of the textgenerator plugin, where only a few simple settings are needed to use other services compatible with the OpenAI API. This usually includes Endpoint, Apikey, context and Model name.

**Comment by cephalization** [comment]
See #28 should be merged in soon.

Not sure the floodgates should open totally just yet on fully custom models but that PR will get us a lot closer to that idea

**Comment by cibernicola** [comment]
It would be nice to have custom configurations for LM Studio

**Comment by cephalization** [comment]
LM Studio looks very nice. I will look into integration feasibility at some point in the next few weeks

**Comment by cibernicola** [comment]
If I can help somehow, tell me

**Comment by cibernicola** [comment]
LMS Uses the OpenAI framework (I think), 0 langchain, I think that's the right way.
For example, in the previous version, changing, simply the url, everything worked correctly with LM studio, that is, at least in that version, the structure was identical, what changed was the "server" endpoint.

**Comment by cephalization** [comment]
If it is compatible with the openai client, then I should be able to just add a case for LM Studio and return / use the openai client through langchain.

What settings would you need to support LM Studio, assume we have a new option in the dropdown.

Just Base URL?

**Comment by cibernicola** [comment]
This is what I changed in 1.6.1 (same endpoint twice) and it works. With the current version it does not. I have not looked deeper. I can only say what I did worked, but now it doesn't.

![image](https://github.com/DeabLabs/cannoli/assets/4579387/f5f37c21-c43e-4bf5-b5d6-8640e986afec)

**Comment by cibernicola** [comment]
modifications done in v 1.6.1 

main.js
line 11046
`      const options = {
        url: `http://localhost:1234/v1/chat/completions`,
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(rawBody)
      };
      const response = await (0, import_obsidian.requestUrl)(options);
      return response.json;
    } else {
      throw new Error("Invalid LLM provider");
    }`

line 11083

`      const options = {
        url: `http://localhost:1234/v1/chat/completions`,
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify(rawBody)
      };`

**Comment by cibernicola** [comment]
wops! Nice! Again, if I can help, be sure, I Will :)

**Comment by cephalization** [comment]
@cibernicola https://github.com/DeabLabs/cannoli/pull/34/commits/f64050c4f574ed746ab56d5d6e430b77ca532d30

Feel free to copy these changes in. I did not test thoroughly so feel free to report any bugs you find 😅 I will do more thorough testing and a formal release in the next day or two.

Then I will add first class LM Studio support so that you can save settings separately from openai within cannoli settings.

**Comment by cephalization** [comment]
Just make sure you enable CORS in LM Studio or obsidian may refuse to connect to it

**Comment by cibernicola** [comment]
doing your suggestion I get:

from LMStudio
```
[2024-05-15 17:34:39.409] [ERROR] Unexpected endpoint or method. (OPTIONS /api/chat). Returning 200 anyway
[2024-05-15 17:35:10.378] [ERROR] Unexpected endpoint or method. (OPTIONS /api/chat). Returning 200 anyway
[2024-05-15 17:36:48.092] [ERROR] Unexpected endpoint or method. (OPTIONS /api/chat). Returning 200 anyway
```
from Cannoli: 
```
<u>Error:</u>
Error calling LLM:
Failed to fetch
```
If I change:

```
async function* createOllamaGenerateStream(baseUrl, params, options) {
  yield* createOllamaStream(`**http://localhost:1234/v1/chat/completions**`, params, options);
}
async function* createOllamaChatStream(baseUrl, params, options) {
  yield* createOllamaStream(`**http://localhost:1234/v1/chat/completions**`, params, options);
}
```

I get from LM Studio:
```
[2024-05-15 17:39:39.611] [INFO] [LM STUDIO SERVER] Processing queued request...
[2024-05-15 17:39:39.612] [INFO] Received OPTIONS request to /v1/chat/completions with body: {}
[2024-05-15 17:39:39.613] [ERROR] 'messages' field is required
```

:S

**Comment by cephalization** [comment]
<img width="543" alt="Screenshot 2024-05-15 at 12 09 46 PM" src="https://github.com/DeabLabs/cannoli/assets/8948924/dda7603a-8d0d-472c-a821-992738b9b2cf">

that sounds like cors issues to me, try turning this on

**Comment by cibernicola** [comment]
Well, almost there, actually:

CORS On

http://localhost:1234/v1/chat/completions  in both functions and as an option inside ChatOpenAI object, Canoli sends, LMS recives, processes, and also sends the results, but canoli can't(?) retrive the final answer :S 

I mean, is a step closer, but one step more is needed.

**Comment by cephalization** [comment]
I wonder if there is additional code that needs to change after transpilation. It is very hard to debug code changes after transpilation.

It works locally for me, but I am rebuilding the code.

We plan to get a release out later today, that should include these changes

**Comment by cibernicola** [comment]
I'll be watching!!

Deep thanks!

**Comment by cephalization** [comment]
@cibernicola the feature has been deployed to the newest version of cannoli. Let us know how it goes! You can configure the openai base url within settings and set them to localhost:1234 for LM Studio

My plan is to add a dedicated LM Studio dropdown so that you don't have to override your openai config

**Comment by cibernicola** [comment]
Working! (at least this hello world :))
![image](https://github.com/DeabLabs/cannoli/assets/4579387/311099d6-ae17-4628-8e0a-3e6eb9364cd0)

**Comment by cibernicola** [comment]
sure, it supports that. 

check this out:
https://lmstudio.ai/docs/local-server

**Comment by cephalization** [comment]
Awesome, thanks for the reference
