### ISSUE TITLE
A few errors

### ISSUE THREAD

**Issue by arminta7** [DeabLabs/cannoli#32]
1. When I try to run any of the Cannoli College workflows they are just blank (even though it says completed).
2. When I try to run the dataview cannoli I get these errors:

<img width="377" alt="Screenshot 2024-05-10 at 09 43 12" src="https://github.com/DeabLabs/cannoli/assets/7927356/c9e7fa66-855e-436a-b3a4-b998f0b3a162">

**Comment by blindmansion** [comment]
Thanks for letting me know, working on this now

**Comment by cephalization** [comment]
@arminta7 can you share which LLM Provider and Model settings you are using for cannoli?

`openai: gpt-3.5-turbo` for example

**Comment by cephalization** [comment]
Oh, operating system you are running on would be helpful as well. Struggling to replicate myself on Mac OS with openai or ollama

**Comment by arminta7** [comment]
<img width="836" alt="Screenshot 2024-05-10 at 11 22 07" src="https://github.com/DeabLabs/cannoli/assets/7927356/c3adc8d4-1982-44bb-be11-20c6e8864d76">

Mac OS Sonoma 14.5

**Comment by cephalization** [comment]
Awesome, thanks! Do you happen to have any other plugins enabled that manipulate the canvas?

**Comment by arminta7** [comment]
I had Canvas Daily Note, but disabled it and no change. The colors change when I run the cannoli, but no text appears.

**Comment by cephalization** [comment]
Also check if you have this enabled

<img width="778" alt="Screenshot 2024-05-10 at 11 27 15 AM" src="https://github.com/DeabLabs/cannoli/assets/8948924/b8f56d84-8ef5-4da6-80d3-e3fa9d3bfae7">

If so, most of the college will not work at the moment

**Comment by arminta7** [comment]
I disabled that setting. No change for normal cannolis. I got this for the dataview one:

<img width="355" alt="Screenshot 2024-05-10 at 11 36 31" src="https://github.com/DeabLabs/cannoli/assets/7927356/fcea538f-3cc9-440a-8f88-c1141e81523e">

**Comment by cephalization** [comment]
I got that issue myself when the dataview plugin was not installed / disabled? Can you double check that you have it installed and enabled from the community plugins list?

**Comment by arminta7** [comment]
It's definitely installed. I can see the queries. 

<img width="800" alt="Screenshot 2024-05-10 at 11 40 23" src="https://github.com/DeabLabs/cannoli/assets/7927356/03bab9e5-6702-424f-9da1-1447c2a30de2">

**Comment by arminta7** [comment]
I also just disabled most of my other plugins and no change.

**Comment by arminta7** [comment]
One of them just worked! Could it be something with the model config/name?

<img width="820" alt="Screenshot 2024-05-10 at 11 46 15" src="https://github.com/DeabLabs/cannoli/assets/7927356/144f6ec4-4d40-4b64-a90c-8672917e2a90">

**Comment by arminta7** [comment]
Strangely enough, the other workflow on the same page as the one I shared was successful too...

**Comment by cephalization** [comment]
But still the dataview one is busted for you?

**Comment by arminta7** [comment]
Yep, just tried again. I went and set up a new API Key just to be sure and that didn't help. Some of the cannolis are working for me, but not the basic hello world one or the dataview one or the Creating Notes one. Not sure why some and not others.

**Comment by arminta7** [comment]
Changing the model name in settings did not fix it.

**Comment by cephalization** [comment]
We are thinking we will just disable dataview support for now while we debug this issue so that cannoli will still work for other canvases.

Sorry for the interruption, will ping you when the release comes out!

**Comment by cephalization** [comment]
@arminta7 we just pushed the release disabling dataview, if you could give that a try and let us know how it goes that would be awesome 🙏🏽

**Comment by arminta7** [comment]
The Hello World and Blank Arrows cannolis still do not provide any output. The colors do change. No console errors.

**Comment by arminta7** [comment]
I am on Obsidian 1.6 if that makes any difference.

**Comment by cephalization** [comment]
Good callout, I am on obsidian 1.5 let me upgrade

**Comment by cephalization** [comment]
Is 1.6 a beta version of obsidian? I don't see it when I upgrade

**Comment by arminta7** [comment]
Yes, insider build.

**Comment by cephalization** [comment]
We don't have access to the insider builds in order to know if they changed something on their end that could break cannoli functionality. This may explain why we are having trouble replicating.

**Comment by blindmansion** [comment]
We're looking at the 1.6 changelog now. Could you send a few screenshots or maybe a gif of what's happening?

**Comment by arminta7** [comment]
I’m not at my computer now, but the cannolis are pretty simple. When I press start the colors cycle through as normal but no text is ever added by the llm. I can share a recording later if that’s not enough. On May 10, 2024, at 13:18, blindmansion ***@***.***> wrote:﻿
We're looking at the 1.6 changelog now. Could you send a few screenshots or maybe a gif of what's happening?

**Comment by blindmansion** [comment]
Huh. If that switch color parsing setting if off then this is likely something in 1.6. In the meantime maybe you could use the BRAT plugin to install the 1.6.1 version of cannoli, using the "Install beta plugin with frozen version" button.

We'll update if we're able to find a fix. Thanks for working with us here!

**Comment by arminta7** [comment]
Ok, so I don't know what did what, but I downgraded then re-updated to 1.7.4. I deleted the cannoli college folder and re-added it. Now the basic cannolis are working. Yay!

**Comment by arminta7** [comment]
Also, the dataview cannoli is now working for me on 1.7.1. 🎉

**Comment by cephalization** [comment]
Good to hear! We will fix some lingering bugs discovered with the dataview integration in the next few days and send that back out as a new release.

Thanks so much for reporting this and working with us to make cannoli better!
