### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by danbri** [DeabLabs/cannoli#4]
I'm still learning all of this. I've used Obsidian for a while but not in power-user mode, and hadn't tried Canvas either.

I made a couple nodes based on the "2. writing to nodes" sample, I'm sure I'll figure out my mistakes eventually but just wanted to share that the error message,

> <u>Error:</u>
> Error calling LLM:
> [] is too short - 'messages'

Is pretty cryptic. It tells me that something is missing somewhere. Is it possible to say more here?

**Comment by blindmansion** [comment]
Thanks for giving cannoli a try! This error message is actually coming from the openai api, I believe it means that no messages were sent. It is pretty cryptic, I can see about catching this and displaying better error message.

Empty call nodes will not add any messages to the messages array, so if there are no messages coming from other nodes, nothing will be sent to the openai api, resulting in this error.

Can you share a screenshot of the cannoli that's producing this?

**Comment by blindmansion** [comment]
You can print a log of all the messages sent to openai using a logging arrow, which is an orange arrow pointing from the call node to a content node (purple).

In the case of the error above, this likely wouldn't work because the error would happen in the call node itself.
