### ISSUE TITLE
anthropic claude not working

### ISSUE THREAD

**Issue by winne617** [DeabLabs/cannoli#41]
hey, openai works fine, with claude i get nothing out of it but an error message
![image](https://github.com/DeabLabs/cannoli/assets/131215156/d50cb552-dd4d-4c00-a1b4-10599533aa66)

api-key and model name ("claude-3-5-sonnet-20240620", "claude-2.1" etc) seem not to be the issue. any idea?

**Comment by cephalization** [comment]
We've spotted this internally but haven't had the chance to really come up with a great fix.

The main issue is that anthropic servers enforce CORS security, which is somewhat of a non starter in obsidian plugins unless you use a special API that can circumvent that security.

As the plugin attempts to treat all providers generically, it is difficult to special case anthropic and use obsidian's cors workaround for LLM calls using Claude.

We are still thinking of the best way around this problem, sorry for the inconvenience

**Comment by winne617** [comment]
good luck! hope you'll manage to solve that somehow;) thanks for the plugin anyway

**Comment by Dvoznesensky-SW** [comment]
Can you share a "not great" kinda fix while we waiting for a good one? 3.5 sonnet is my go to model, feels weird to switch to openai for this

**Comment by cephalization** [comment]
I hear you @Dvoznesensky-SW I think I may have something for you in the next day or two

**Comment by arminta7** [comment]
Somewhat related, I tried Claude 3.5 sonnet through OpenRouter to get around this and was having an issue with function calling.

**Comment by cephalization** [comment]
@Dvoznesensky-SW @winne617 give cannoli 2.0 a try for Claude. It requires a free val.town account and API key. Once configured, cannoli can setup a free proxy for your to route all anthropic calls through. There is a button right in the anthropic settings section to setup the proxy for you

**Comment by Dvoznesensky-SW** [comment]
Wow thanks, looking forward to dig into all new features. As for Anthropic, it works, but i had a little issue with valtown api key, had to delete default ones and create new one

**Comment by cephalization** [comment]
@Dvoznesensky-SW can you elaborate? are you saying there was a prefilled api key for val town within cannoli already?

**Comment by blindmansion** [comment]
Anthropic is now enabled without the need for the proxy
