### ISSUE TITLE
Bug: Duplicate file names cause incorrect references in Dataview query results.

### ISSUE THREAD

**Issue by Hwenyi** [DeabLabs/cannoli#49]
In my vault, I have many practice questions, they are all named by question number and placed in different folders. 
When I use `dataview` in the reference node and use dataview in the action node, both will cause incorrect reference problems:
For example, I want to search for the questions I got wrong from the folder shown in the picture. 
These should all be computer-related questions, but it will incorrectly extract and reference questions with the same name and number from another mathematics folder. 
I have tried many `dataview` ways to try to make it reference with an absolute path, but they all failed.
Oh, by the way, if you click directly on the result searched by `dataview`, it will be the correct file referenced by the absolute path, but when it is passed as a content variable node that needs to be extracted, it will extract other files with the same name incorrectly.
![image](https://github.com/user-attachments/assets/11864056-7bbf-4ed1-bde5-fb3c14215c51)
This is because when you code, you only use the file name to pass the variable, resulting in the inability to identify files with the same name?

**Comment by blindmansion** [comment]
Hi Hwenyi! Can you paste your full dataview query in here so I can see if I can replicate this issue?

**Comment by Hwenyi** [comment]
It's quite simple, the dataview query to search for notes containing either tag A or B in the specified path is

```dataview
LIST WITHOUT ID file.link
FROM "刷题/408做题本/25王道/25计组-王道/第 7 章 IO 系统"
WHERE contains(file.tags, "#做错了") OR contains(file.tags, "#犹豫")
```

The query results, when within the Obsidian, correctly display files located under the proper path and are rendered accurately. However, once these results are passed into Cannoli, they fail to carry over the path information. 
Instead, Cannoli defaults to overwriting identically named files from the entire vault, consequently passing an incorrect file.

![image](https://github.com/user-attachments/assets/16ba664a-d2dd-4eeb-ae73-4c0a15f1886c)

**Comment by Hwenyi** [comment]
> Hi Hwenyi! Can you paste your full dataview query in here so I can see if I can replicate this issue?嗨 Hwenyi！你能在这里粘贴你的完整 dataview 查询，这样我就可以看看我是否能复制这个问题吗？

It's quite simple, the dataview query to search for notes containing either tag A or B in the specified path is

```dataview
LIST WITHOUT ID file.link
FROM "刷题/408做题本/25王道/25计组-王道/第 7 章 IO 系统"
WHERE contains(file.tags, "#做错了") OR contains(file.tags, "#犹豫")
```

The query results, when within the Obsidian, correctly display files located under the proper path and are rendered accurately. However, once these results are passed into Cannoli, they fail to carry over the path information. 
Instead, Cannoli defaults to overwriting identically named files from the entire vault, consequently passing an incorrect file.

![image](https://github.com/user-attachments/assets/16ba664a-d2dd-4eeb-ae73-4c0a15f1886c)

**Comment by blindmansion** [comment]
Ok cool I understand now. Yea maybe we're somehow changing the path or otherwise handling it incorrectly before it gets injected in the dataview query, I'll look into this more.

**Comment by Hwenyi** [comment]
> Ok cool I understand now. Yea maybe we're somehow changing the path or otherwise handling it incorrectly before it gets injected in the dataview query, I'll look into this more.

I've encountered a similar issue with the bug: If only the current file's name is extracted, using the `{{Note}}` variable for referencing can inadvertently link to another file with the same name.

**Comment by blindmansion** [comment]
@Hwenyi This should be fixed now! Turned out to be a one-line change haha. As you said, we were not handling filepath links correctly, which was removing the path information from the file link.

Let us know if it works as expected!
