### ISSUE TITLE
How to disable the vision model?

### ISSUE THREAD

**Issue by Hwenyi** [DeabLabs/cannoli#52]
In articles with images, I do not want LLM to recognize the images within, or I want a LLM without multimodal capabilities to read the pure text of the notes directly without triggering the vision mode. 
Because when I try to process the notes using a model that only inputs pure text, I find that now it always requests the vision model due to the presence of images in the notes, but the LLM I set does not have multimodal capabilities, which causes errors.
I haven't found any information in the release notes or issues about how to close the vision mode or how a pure text LLM can read notes with images. I would like to know if this feature hasn't been implemented yet, or if it's already possible to manually set the vision model to be turned off.

**Comment by cephalization** [comment]
Thanks for bringing this up, pretty large oversight on our part.

We will get started on some settings that can disable vision models globally as well as config node settings to turn it back on by node or group

**Comment by blindmansion** [comment]
@Hwenyi This setting is now up! You can disable vision globally in the settings tab, or define it on a node-level using an "enableVision" config arrow (check out how to do this in the vision canvas of the cannoli college).
