### ISSUE TITLE
Append output to a note

### ISSUE THREAD

**Issue by OCEISCO** [DeabLabs/cannoli#56]
I'm trying to process a list of text in a workflow, but I need to run it with different sets of documents. The current implementation processes each item individually, which works for me. However, I'd like to save the results to the same document instead of overwriting them.

Can you help me understand how to append the results to an existing document? Is there a specific append or update action that can be used in the workflow?

Additionally, is it possible to run a loop on a list where each result is added as a new note? I'd like to keep track of all the processed documents and their corresponding results.
thank you

**Comment by blindmansion** [comment]
Hello @OCEISCO!

There's currently not a built-in way to append to a note, but you can achieve the same thing using formatter nodes, like this:
![image](https://github.com/user-attachments/assets/44c57aa9-6319-41e7-ac35-676cdaa20ef0)

Here we're creating a new version of the note using a formatter node (the double-double quotations in a content node) by injecting the current content and the new content after it. Then we overwrite the note with that new version using a reference node (a content node with just a single note reference in it).

As for creating a new note for each run, you can use the note creation syntax here (this is on 4.4 of the cannoli college).
![image](https://github.com/user-attachments/assets/b9f3dedc-aca2-473e-9fa9-310d587c717b)

Let me know how this works for you, happy to answer other questions.

**Comment by OCEISCO** [comment]
Apologies for open this again. Thank you, the double quotation is kind of what I was looking for. I am wondering if double quotation formatter can be a formal method to identify a note node that will always wrap itself (the current data) every run, as the "intro" for the incoming data to be append?
