### ISSUE TITLE
[Feature request] Add a configurable "OpenAI" endpoint URL to support local LLMs

### ISSUE THREAD

**Issue by amitkot** [DeabLabs/cannoli#9]
Running local LLMs locally using tools such as [ollama](https://ollama.ai/) improves both cost and privacy.
The tools expose the same REST api as OpenAI and allowing the user to configure a local endpoint is all it takes to use them instead of OpenAI.

**Comment by blindmansion** [comment]
This has definitely been on my own wishlist, and ollama seems to make it a lot easier. I'll take a look, thanks!

**Comment by cephalization** [comment]
@amitkot it appears that Ollama is _not_ yet a drop-in replacement for the openai client API https://github.com/jmorganca/ollama/issues/305 which would make this quite an easy change.

Switching to some backend agnostic LLM query client does seem like a great idea though. I will spike a PR that investigates how much work that would take.

**Comment by cephalization** [comment]
Got it working minimally #22

Will continue polishing it up with @blindmansion and get it ready for use assuming we don't find any major showstoppers

**Comment by wwjCMP** [comment]
LM Studio also provides OpenAI-compatible agents and hopes to increase support for it

**Comment by cephalization** [comment]
@amitkot this is finally available, sorry for the wait! It does not currently support function calling at the moment, but it should be a fast follow within the week.

**Comment by wwjCMP** [comment]
https://github.com/songquanpeng/one-api 
This project can convert ollama into a way that is compatible with the OpenAI API.

**Comment by amitkot** [comment]
@cephalization thanks! I'll try it out 🙏

**Comment by cephalization** [comment]
@wwjCMP I am looking into some options like this so that expanding LLM support is very easy, and we don't have to turn off features like function calling. Probably should have just started with Langchain 😅

**Comment by cephalization** [comment]
Adding support for even more providers and function calling in #28
